//! Strongly-typed identifier newtypes wrapping [`Uuid`].
//!
//! Four ID types — [`AgentId`], [`ToolId`], [`SkillId`], and [`CapabilityId`] —
//! are generated by the `newtype_id!` macro. Each is a transparent newtype
//! over `Uuid` with `Display`, `Serialize`/`Deserialize`, and `Hash` impls.

use serde::{Deserialize, Serialize};
use std::fmt;
use std::str::FromStr;
use uuid::Uuid;

/// Generates a newtype wrapper around [`Uuid`] with common trait impls.
///
/// Each generated type provides `new()` (random v4), `from_uuid()`,
/// `as_uuid()`, `Display`, `Default`, `Hash`, and serde support.
macro_rules! newtype_id {
    ($name:ident) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
        #[serde(transparent)]
        pub struct $name(Uuid);

        impl $name {
            pub fn new() -> Self {
                Self(Uuid::new_v4())
            }

            pub fn from_uuid(uuid: Uuid) -> Self {
                Self(uuid)
            }

            pub fn as_uuid(&self) -> &Uuid {
                &self.0
            }
        }

        impl Default for $name {
            fn default() -> Self {
                Self::new()
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                write!(f, "{}", self.0)
            }
        }

        impl FromStr for $name {
            type Err = uuid::Error;
            fn from_str(s: &str) -> std::result::Result<Self, Self::Err> {
                Ok(Self(Uuid::parse_str(s)?))
            }
        }
    };
}

newtype_id!(AgentId);
newtype_id!(ToolId);
newtype_id!(SkillId);
newtype_id!(CapabilityId);
newtype_id!(SessionId);
newtype_id!(MessageId);
newtype_id!(MemoryId);
newtype_id!(TripleId);
newtype_id!(TaskId);
newtype_id!(NotificationId);
newtype_id!(TenantId);
newtype_id!(OutcomeId);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ids_are_unique() {
        let a = AgentId::new();
        let b = AgentId::new();
        assert_ne!(a, b);
    }

    #[test]
    fn id_display_is_uuid_format() {
        let id = AgentId::new();
        let s = id.to_string();
        assert!(Uuid::parse_str(&s).is_ok());
    }

    #[test]
    fn id_serde_roundtrip() {
        let id = ToolId::new();
        let json = serde_json::to_string(&id).unwrap();
        let parsed: ToolId = serde_json::from_str(&json).unwrap();
        assert_eq!(id, parsed);
    }
}
